version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: danylevych/node_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_app_db
      - PG_USER=danylevych
      - PG_PASSWORD=12345
      - PG_HOST=node_app_db
    depends_on:
      - node_app_db
  
  node_app_db:
    container_name: node_app_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_app_db
      - POSTGRES_USER=danylevych
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
